### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by Infra101** [Beckhoff-USA-Community/TcHmiCncControls#2]
Hi Team.

First of all, I want to commend you on the great work you’re doing here! The project looks fantastic, and I’ve been enjoying using it.

I did encounter small issues, though. When I add various GCodes to the editor, the rendering appears differently from my current software. For example, some circles seem to be out of place, and in certain cases, G0 rapid transverse lines are being interpreted as cutting lines.

To help illustrate the problem, I'll upload some images and a sample of the GCode I’m working with. I hope this helps in diagnosing the issue.

Thanks again for all your hard work!

Best regards,

[1stGcode.txt](https://github.com/user-attachments/files/16998547/1stGcode.txt)
![1stGcodeRenderer](https://github.com/user-attachments/assets/9298df7f-db8f-42c5-8c75-09d6806d7842)
![1stGcodeSoftware](https://github.com/user-attachments/assets/722d4e33-4dea-4007-afeb-1703d536604c)
[2ndGcode.txt](https://github.com/user-attachments/files/16998548/2ndGcode.txt)
![2ndGcodeSoftware](https://github.com/user-attachments/assets/9ca15b12-752e-45a0-9dfd-5b586bde1931)
![2ndSoftwareRenderer](https://github.com/user-attachments/assets/31fcb825-b801-4891-a041-dbd979ac4322)

**Comment by bstiffler582** [comment]
Thanks for the heads up. This was a bug in arc center point calculation using relative I/J/K values. Most of my testing so far has been with absolute. Fixed in latest push [39abd87](https://github.com/Beckhoff-USA-Community/TcHmiCncControls/commit/39abd87b710ce6871c43d4c04e9eb66db36b5f4c).
